### PR TITLE
fix events subscription from other phases

### PR DESCRIPTION
**Pull request by paulormart**
With this change System events like `staking::events::EraPaid`, `session::events::NewSession`, `grandpa::events::NewAuthorities` can be subscribed, otherwise they are currently being skipped using the pseudo code below:

```
let client = self.client();
let sub = client.rpc().subscribe_finalized_events().await?;
let decoder = client.events_decoder();
let mut sub = EventSubscription::<DefaultConfig>::new(sub, &decoder);
sub.filter_event::<node_runtime::staking::events::EraPaid>();
while let Some(result) = sub.next().await {
    if let Ok(raw) = result {
        match node_runtime::staking::events::EraPaid::decode(&mut &raw.data[..]) {
            Ok(event) => info!("Successfully decoded event {:?}", event),
            Err(e) => error!("Error decoding event {:?}", e),
        }
    }
}
```

### CODE REVIEW

**Comment by paulormart** [comment]
reference to pull request #294

**Comment by sander2** [comment]
This is a duplicate of https://github.com/paritytech/subxt/pull/283, but this will definitely be good to merge into the open PR

**Comment by paulormart** [comment]
@ascjones `master` branch targeted

**Comment by ascjones** [comment]
Closing as duplicate of #283

**Pull request closed without merging**
