### PR TITLE
Add `--derive-for-type` to cli

### PR DESCRIPTION
**Pull request by fmiguelgarcia**
# Description
Add `--derive_for_type` to the `cli`

# Example
```
subxt codegen \
   --derive Clone \
   --derive PartialEq \
   --derive Eq \
   --derive-for-type my_module::my_type_1=serde::Serialize \
   --derive-for-type my_module::my_type_1=serde::Deserialize \
   --derive-for-type my_module::my_type_1=Default \
   --url http://localhost:9933 \
   | rustfmt --edition=2021 --emit=stdout > api.rs
```

### CODE REVIEW

**Comment by jsdw** [comment]
Ah, I didn't notice but your branch but be lagging behind master somewhat. Please update to the latest master and reapply your changes in the relevant place and it should be good to go; logic wise it looks sound :)

**Review by jsdw — APPROVED** [review]
Works for me; thank you for your contribution!

**Comment by jsdw** [comment]
Just need to run a `cargo clippy --all-targets` and fix the error (or look at the CI output from that job) and this should be good to go!

**Comment by jsdw** [comment]
Ah, no, it's just a dumb unrelated clippy error; I'll have a look tomorrow!

**Comment by fmiguelgarcia** [comment]
@jsdw I removed some clippy warnings. Let's see it CI passes now.

**Review by niklasad1 — APPROVED** [review]

**Pull request merged**
