### PR TITLE
chore: bump sp-core, sp-runtime and sp-keyring

### PR DESCRIPTION
**Pull request by niklasad1**

### CODE REVIEW

**Review by jsdw — APPROVED** [review]

**Comment by niklasad1** [comment]
it's seems like these bump leaks the `--feature std` in the workspace which breaks the no-std stuff

**Review by lexnv — APPROVED** [review]

**Comment by jsdw** [comment]
Oh strange; I wonder whether their default features changed or something then; it'd be great to find out anyway. There's no urgent rush in getting the release out if we can fix this one first :)

**Comment by niklasad1** [comment]
I think it's should be fine after you moved sp-crypto-hashing, tested it locally

**Comment by jsdw** [comment]
Oh interesting; not sure why that would have made a difference but hey ho :)

**Pull request merged**
