### PR TITLE
fix extrinsics retracted

### PR DESCRIPTION
**Pull request by paulormart**
Since `Retracted` extrinsics may fit in a different block, i think there is no need to raise an error, just wait until it gets a `Finalized`, `Dropped` or `FinalityTimeout`.

In this way the caller most likely will get the finalised block for the specific extrinsic and do not lose it's sight.

### CODE REVIEW

**Comment by paulormart** [comment]
reference to pull request #294

**Comment by ascjones** [comment]
Please target `master` now

**Comment by h4x3rotab** [comment]
A rebase to master would be nice

**Review by ascjones — APPROVED** [review]
LGTM.

Though this highlights again the inadequacy of this API, I'm thinking we should give more control to the user by accessing the `TransasctionStatus` as part of the events subscription, then they can react as they choose. I will open an issue for this soon.

**Review by niklasad1 — APPROVED** [review]

**Pull request merged**
