### PR TITLE
expose jsonrpc-core client

### PR DESCRIPTION
**Pull request by seunlanlege**
We depend on the jsonrpc-core client so we can make typed rpc requests

eg: https://github.com/ComposableFi/hyperspace/blob/311bc18ac6d4b24ed4586ba98552e9e145b0b068/parachain/src/provider.rs#L335-L342

### CODE REVIEW

**Comment by niklasad1** [comment]
There is already an `Deref impl` for the rpc client, why can't you use that?

**Comment by jsdw** [comment]
How about instead of this, the existing Deref impl returns `&Arc<dyn RpcClientT>` rather than `dyn rpcClientT` as it does at the mo? Arc has a deref anyway so it shouldn't alter anything, and it'll give you access to the arc you can clone or whatever without exposing any "internals"? Feels a bit cleaner at least to me :)

**Comment by jsdw** [comment]
Though another approach for you may just be to clone and keep hold of a copy of the original `Client` itself rather than having to cast a `dyn RpcClientT`? This may mean constructing it explicitly and then initialising the `OnlineClient` with it, but if you want access to the same client subxt is using, that is probably the safest option.

**Comment by seunlanlege** [comment]
> Another, safer, approach for you may just be to clone and keep hold of a copy of the original jsonrpsee Client itself rather than having to cast a dyn RpcClientT? This means constructing it explicitly and then passing it to the OnlineClient::from_rpc_client method (as well as cloning it to keep separately), but if you want access to the same client subxt is using, that is probably the safest option and avoids any casting (which may break in the future) or whatever

I've modified the PR with this approach

**Review by niklasad1 — APPROVED** [review]
LGTM, just to run `cargo fmt` to make the CI happy.

**Review by jsdw — APPROVED** [review]
LGTM once fmt is ran and we've fixed our tests.

**Comment by seunlanlege** [comment]
> LGTM, just to run cargo fmt to make the CI happy.

Done 🙏🏿

**Pull request merged**
