### PR TITLE
fix: cache extrinsic events

### PR DESCRIPTION
**Pull request by f-squirrel**

### CODE REVIEW

**Review by niklasad1 — APPROVED** [review]
nice catch, thanks

**Comment by f-squirrel** [comment]
> nice catch, thanks

Thank you. I have fixed Clippy; please review-rerun the CI.

**Comment by f-squirrel** [comment]
@niklasad1 , it seems I am missing something here.
The CI fails on Clippy for the code that I did not change.
Is it supposed to be like that?

**Comment by niklasad1** [comment]
@f-squirrel 

It's the new rustc release that caused lemme fix that and not related to your PR, sorry

**Review by jsdw — APPROVED** [review]
Whoops, thank you :)

**Pull request merged**
